# Generated by Django 5.2.8 on 2025-12-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='first_name',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='is_staff',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='is_superuser',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='last_name',
            field=models.CharField(null=True),
        ),
    ]
