# Generated by Django 5.2.8 on 2025-12-16 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customusers_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='username',
        ),
    ]
