# Generated by Django 5.2.8 on 2025-12-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_customusers_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='email',
            field=models.EmailField(max_length=256, null=True, unique=True),
        ),
    ]
