# Generated by Django 5.2.8 on 2025-12-16 02:29

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_customusers_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customusers',
            managers=[
                ('objects', api.models.CustomUserManager()),
            ],
        ),
    ]
