# Generated by Django 5.2.8 on 2025-12-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customusers_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='username',
            field=models.CharField(null=True),
        ),
    ]
