# Generated by Django 5.2.8 on 2025-12-18 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customusers_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.PositiveIntegerField(unique=True)),
                ('is_booked', models.BooleanField(default=False)),
                ('booking_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'slots',
                'constraints': [models.CheckConstraint(condition=models.Q(('slot_number__gte', 1), ('slot_number__lte', 1000)), name='slot_number_range_1_1000')],
            },
        ),
    ]
