# Generated by Django 5.2.8 on 2025-12-18 15:50

from django.db import migrations

def create_slots(apps, schema_editor):
    Slot = apps.get_model("api", "Slot")

    Slot.objects.bulk_create(
        [Slot(slot_number=i) for i in range(1, 1001)],
        ignore_conflicts=True
    )
class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_slot'),
    ]

    operations = [
        migrations.RunPython(create_slots,migrations.RunPython.noop)
    ]
