# Generated by Django 5.2.8 on 2025-12-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_create_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='hold_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10),
        ),
        migrations.AddField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('pending', 'Pending Approval'), ('booked', 'Booked')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
