# Generated by Django 5.2.8 on 2026-01-01 08:13

import django.db.models.deletion
import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_slot_hold_until_slot_price_slot_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_name', models.CharField(max_length=255)),
                ('upi_account_name', models.CharField(max_length=255)),
                ('payment_app', models.CharField(choices=[('gpay', 'Google Pay'), ('phonepe', 'PhonePe'), ('paytm', 'Paytm')], max_length=20)),
                ('verification_token', models.CharField(default=secrets.token_urlsafe, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'manual_bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['slot_number']},
        ),
        migrations.RemoveConstraint(
            model_name='slot',
            name='slot_number_range_1_1000',
        ),
        migrations.AlterField(
            model_name='slot',
            name='slot_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manualbooking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_bookings', to='api.slot'),
        ),
        migrations.AddField(
            model_name='manualbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manualbooking',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
