# Generated by Django 5.2.8 on 2026-01-17 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_manualbooking_alter_slot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualbooking',
            name='amount',
            field=models.IntegerField(default=2000, help_text='Amount must be at least 2000', validators=[django.core.validators.MinValueValidator(2000)]),
            preserve_default=False,
        ),
    ]
